#define LOOSE_COND	(14)
#define	BUFFLEN		(32)
#define	NB_BOATS	(4)
#define	LINELEN		(BUFFLEN/NB_BOATS)
#define	BOARD_LINE	(&buffer[line * LINELEN])
#define	DELIM_A		(1)
#define	DELIM_B		(4)
#define	BSIZE		(8)
